version: '3.9'

services:
  event-service:
    container_name: event-service
    build:
      context: ./event-service
    ports: 
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - postgres-db
  
  postgres-db:
    container_name: postgres-db
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}

volumes:
  postgres-db: