version: '3.8'

services:
  event-service:
    container_name: event-service
    build:
      context: ./event-service
    environment:
      DATABASE_URL: mongodb://mongo-db:27017/events
      SECRET_KEY: ${SECRET_KEY}
    ports: 
      - 5000:5000
    depends_on:
      - mongo-db
  
  mongo-db:
    container_name: mongo-db
    image: mongo:latest
    restart: always
    volumes:
      - mongo-db:/data/db
    ports:
      - 27017:27017

volumes:
  mongo-db